core/urls.py
from xml.dom.minidom import Document
from django.urls import path
from . import views
from lms.settings import MEDIA_URL,MEDIA_ROOT, STATIC_ROOT, STATIC_URL
from django.conf.urls.static import static

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('catalog/', views.catalog, name='catalog'),
    path('book/<str:uuid>/',views.details,name='details'),
    path('request_book/<str:uuid>/', views.request_book, name='request_book'),
    path('new_book/', views.new_book, name='new_book'),
    path('return_book/<str:uuid>/', views.return_book, name='return_book'),
    path('take_book/<str:uuid>/', views.take_book, name='take_book'),
    path('searched/', views.searched, name='searched'),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

urlpatterns += static(STATIC_URL, document_root=STATIC_ROOT)

lms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('users/',include('users.urls')),
]

users/urls.py
from django.urls import path, include
from.import views
from lms.settings import MEDIA_URL,MEDIA_ROOT, STATIC_ROOT, STATIC_URL
from django.conf.urls.static import static

app_name='users'

urlpatterns = [
    path('login/', views.LoginPageView.as_view(), name='login'),
    path('signup/',views.SignUpView.as_view(), name='signup'),
    path('profile/<int:id>/', views.profile, name='profile'),
    path('signout/', views.signout, name='signout'),
    path('notifications/<int:id>/', views.notifications, name='notifications'),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

urlpatterns += static(STATIC_URL, document_root=STATIC_ROOT)

core/models.py
from django.db import models
from users.models import CustomUser
import uuid
from datetime import datetime

genres = [
    ('SciFi', 'SciFi'),
    ('Romance', 'Romance'),
    ('Thriller', 'Thriller'),
    ('Kids', 'Kids'),
    ('Educational', 'Educational'),
    ('Memoir', 'Memoir'),
    ('Business', 'Business'),
    ('Action', 'Action'),
]

status_choices = [
    ('A', 'Available'),
    ('R', 'Requested'),
    ('T', 'Taken')
]

class Book(models.Model):
    title = models.CharField(max_length=50)
    author = models.CharField(max_length=50)
    publisher = models.CharField(max_length=50)
    summary = models.TextField()
    cover_photo = models.ImageField(upload_to="cover_images")
    genre = models.CharField(max_length=20, choices=genres)
    status = models.CharField(max_length=50, choices=status_choices, default='A')
    uuid = models.UUIDField(default=uuid.uuid4)
    borrower = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True)
    date_borrowed = models.DateTimeField(null=True, blank=True, default=None)
    due_date = models.DateTimeField(null=True, blank=True, default=None)
    no_borrowed = models.IntegerField(default=0)

    class Meta:
        permissions = (('can_change_status', 'Change the status of the book'),
                        ('can_request_book', 'Can request for a book to borrow'),
                        ('can_return_book', 'Can return a borrowed book'))

    def __str__(self) -> str:
        return self.title

    @property
    def is_due(self):
        return bool(self.status=='T' and datetime.now() > self.due_date)

class BookInstance(models.Model):
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=63)
    publisher = models.CharField(max_length=63)
    borrower = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    date_borrowed = models.DateTimeField(null=True, blank=True, default=None)

    def __str__(self):
        return self.title 

core/forms.py
from django import forms 
from .models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'author', 'publisher', 'cover_photo', 'genre', 'summary']
        labels = {'title': 'Title', 'author': 'Author', 'publisher': 'Publisher', 
                    'cover_photo': 'Cover Photo', 'genre': 'Genre', 'summary': 'Summary'}
        

core/views.py
from django.shortcuts import render, redirect
from .models import Book, BookInstance
from django.contrib.auth.decorators import login_required, permission_required
from .forms import BookForm
from django.contrib import messages 
from datetime import datetime, timedelta, timezone
import pytz 

def index(request):
    return render(request, 'core/index.html', {})

@login_required
def catalog(request):
    books = Book.objects.all()
    number = Book.objects.count()
    context = {'books':books, 'number': number} 
    return render(request, "core/catalog.html", context)

@login_required
def details(request, uuid):
    book = Book.objects.get(uuid=uuid) 
    userr = None
    if book.status != 'A':
        if book.borrower == request.user:
            userr = request.user
        else:
            context = {'book': book, 'userr': userr}
            return render(request, 'core/details.html', context)
    context = {'book': book, 'userr': userr}
    return render(request, 'core/details.html', context)

@login_required
@permission_required('core.can_request_book')
def request_book(request, uuid):
    book = Book.objects.get(uuid=uuid)
    try:
        book2 = Book.objects.get(borrower=request.user)
    except Book.DoesNotExist:
        book.borrower = request.user
        book.status = 'R'
        book.save()
        return redirect("core:details", uuid=book.uuid)
    else:
        messages.info(request, "Please return the last book you borrowed before borrowing another!")
        return redirect("core:details", uuid=book.uuid)

@login_required
@permission_required('core.add_book')
def new_book(request):
    if request.method != 'POST':
        form = BookForm()
    else:
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('core:index')
    context = {'form': form}
    return render(request, 'core/new_book.html', context)
    

@login_required
@permission_required('core.can_return_book')
def return_book(request, uuid):
    book = Book.objects.get(uuid=uuid)
    book.status = 'A'
    book.borrower = None
    book.no_borrowed += 1
    book.due_date = None
    book.date_borrowed = None
    book.save()
    return redirect('core:details', uuid=book.uuid)

@login_required
@permission_required('core.can_change_status')
def take_book(request, uuid):
    book = Book.objects.get(uuid=uuid)
    book.status = 'T'
    borrow_time = datetime.now().replace(tzinfo=timezone.utc)
    book.date_borrowed = borrow_time
    book.due_date = book.date_borrowed + timedelta(minutes=5)
    print(book.due_date)
    book.save()
    new_inst = BookInstance.objects.create(title=book.title, author=book.author, publisher=book.publisher, borrower=book.borrower, date_borrowed=datetime.now())
    return redirect('core:details', uuid=book.uuid)

def searched(request):
    if request.method == 'POST':
        required = request.POST['search']
        others = None
        try:
            book = Book.objects.get(title__contains=required)
        except Book.DoesNotExist:
            book = None
        else:
            others = Book.objects.filter(genre=book.genre)
        context = {'book': book, 'others': others}
        return render(request, 'core/searched.html', context)

core/templates/core/catalog.html
{% extends "base.html" %}

{% block title %}
    Catalog
{% endblock title %}
{% block content %}
    <p>Browse our databse with over {{ number }} books!</p>
    {% for book in books %} 
        <p>
            <a href="{% url 'core:details' book.uuid %}">
                <img src="{{ book.cover_photo.url }}" alt="No Image Found" width="200" height="200">
                <p>{{ book.title }}</p>
            </a>
            <p>{{ book.author }}</p>
            <p>{{ book.publisher }}</p>
            <p>{{ book.genre }}</p>
            <p>{{ book.get_status_display }}</p>
        </p>
        <br>
    {% endfor %}
{% endblock content %}

core/templates/core/details.html
{% extends "base.html" %}

{% block title %}
    {{ book.title }}
{% endblock title %}

{% block header %}
    <p>
        <a href="{% url 'core:index' %}">LMS</a> - 
        {% if user.is_authenticated %}
            {{ user.username }} - 
            <a href="{% url 'users:signout' %}">Sign Out</a> - 
            <a href="{% url 'core:new_book' %}">Add book</a> -
            {% if user.role == 'Student' %}
                <a href="{% url 'users:profile' user.id %}">Profile</a> -
            {% endif %}
        {% endif %}
    </p>
{% endblock header %}

{% block content %}
    <img src="{{ book.cover_photo.url }}" alt="No Image Found" width="500" height="500">
    <h1>{{book.title}}</h1>
    <p>{{book.author}}</p>
    <p>{{book.publisher}}</p>
    <p>{{ book.summary|linebreaks }}</p>
    <p>Request for book</p>
    {% if book.status == 'A' %}
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        {% if perms.core.can_request_book %}
            <button><a href="{% url 'core:request_book' book.uuid %}">Available</a></button>
        {% endif %}
    {% elif book.status == 'R' %}
        <button type="button" disabled>Requested</button>
        {% if perms.core.can_change_status %}
            <button><a href="{% url 'core:take_book' book.uuid %}">Set Taken</a></button>
        {% endif %}
    {% else %}
        <button type="button" disabled>Unavailable</button>
        {% if userr %}
            <button><a href="{% url 'core:return_book' book.uuid %}">Return</a></button>
        {% endif %}
    {% endif %}
{% endblock content %}

core/templates/core/index.html
{% extends "base.html" %}

{% block title %}
    Library Management System
{% endblock title %}
{% block content %}
    <p>Welcome to the Library!</p>
    <form method="POST" action="{% url 'core:searched' %}">
        {% csrf_token %}
        <label for="search">Search</label>
        <input type="text" name="search" id="search" placeholder="Search for a book" required>
        <br>
        <button name="submit">Search</button> 
    </form>
{% endblock content %}

core/templates/core/new_book.html
{% extends "base.html" %}

{% block title %}
    New Book 
{% endblock title %}

{% block header %}
    <p>
        <a href="{% url 'core:index' %}">LMS</a> - 
        {% if user.is_authenticated %}
            {{ user.username }} - 
        {% endif %}
    </p>
{% endblock header %}

{% block content %}
    <form action="{% url 'core:new_book' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add Book</button>
        <input type="hidden" name="next" value="{% url 'core:index' %}">
    </form>
{% endblock content %}

core/templates/core/searched.html
{% extends "base.html" %}

{% block title %}
    Searched...
{% endblock title %}

{% block content %}
    {% if book %}
        <p>
            <a href="{% url 'core:details' book.uuid %}">
                <img src="{{ book.cover_photo.url }}" alt="No Image Found" width="200" height="200">
                <p>{{ book.title }}</p>
            </a>
            <p>{{ book.author }}</p>
            <p>{{ book.publisher }}</p>
            <p>{{ book.genre }}</p>
            <p>{{ book.get_status_display }}</p>
        </p>
        <hr>
        <h5>Similar titles...</h5>
        {% for book in others %} 
            <p>
                <a href="{% url 'core:details' book.uuid %}">
                    <img src="{{ book.cover_photo.url }}" alt="No Image Found" width="200" height="200">
                    <p>{{ book.title }}</p>
                </a>
                <p>{{ book.author }}</p>
                <p>{{ book.publisher }}</p>
                <p>{{ book.genre }}</p>
                <p>{{ book.get_status_display }}</p>
            </p>
            <br>
        {% endfor %}
    {% else %}
        <p>The book you requested for is Unavailable</p>
    {% endif %}
{% endblock content %}