core/urls.py
from xml.dom.minidom import Document
from django.urls import path
from . import views
from lms.settings import MEDIA_URL,MEDIA_ROOT, STATIC_ROOT, STATIC_URL
from django.conf.urls.static import static

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('catalog/', views.catalog, name='catalog'),
    path('book/<str:uuid>/',views.details,name='details'),
    path('request_book/<str:uuid>/', views.request_book, name='request_book'),
    path('new_book/', views.new_book, name='new_book'),
    path('return_book/<str:uuid>/', views.return_book, name='return_book'),
    path('take_book/<str:uuid>/', views.take_book, name='take_book'),
    path('searched/', views.searched, name='searched'),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

urlpatterns += static(STATIC_URL, document_root=STATIC_ROOT)

lms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('users/',include('users.urls')),
]

users/urls.py
from django.urls import path, include
from.import views
from lms.settings import MEDIA_URL,MEDIA_ROOT, STATIC_ROOT, STATIC_URL
from django.conf.urls.static import static

app_name='users'

urlpatterns = [
    path('login/', views.LoginPageView.as_view(), name='login'),
    path('signup/',views.SignUpView.as_view(), name='signup'),
    path('profile/<int:id>/', views.profile, name='profile'),
    path('signout/', views.signout, name='signout'),
    path('notifications/<int:id>/', views.notifications, name='notifications'),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

urlpatterns += static(STATIC_URL, document_root=STATIC_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

role_choices = [
    ('Librarian', 'Librarian'),
    ('Student', 'Student'),
]

class CustomUser(AbstractUser):
    std_number = models.BigIntegerField(unique=True, null=True, blank=True)
    profile_picture = models.ImageField(upload_to="profile_pictures")
    role = models.CharField(max_length=63, choices=role_choices)

users/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm 
from django.contrib.auth import get_user_model

class LoginForm(forms.Form):
    username = forms.CharField(max_length=63)
    password = forms.CharField(max_length=63, widget=forms.PasswordInput)

class SignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('username', 'std_number','first_name', 'last_name', 'email', 'role', 'profile_picture')

users/views.py
from django.shortcuts import render,redirect
from .models import CustomUser
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from core.models import BookInstance, Book
from .forms import LoginForm, SignUpForm
from django.views.generic import View
from django.contrib.auth.models import Group

class LoginPageView(View):
    form_class = LoginForm
    template_name = 'users/login.html'

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = authenticate(
                username = request.POST['username'],
                password = request.POST['password']
            )
            if user is not None:
                login(request, user)
                return redirect('core:index')
            message = 'login failed'
            return render(request, self.template_name, {'form': form, 'message': message})

class SignUpView(View):
    form_class = SignUpForm
    template_name = 'users/signup.html'

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            role = request.POST['role']
            group = Group.objects.get(name=role)
            user.groups.add(group)
            login(request, user)
            return redirect('core:index')
        return render(request, self.template_name, {'form': form})

def profile(request, id):
    user = CustomUser.objects.get(id=id)
    books = BookInstance.objects.filter(borrower=request.user).order_by('-date_borrowed')
    context = {'user': user, 'books': books}
    return render(request, 'users/profile.html', context)

def signout(request):
    logout(request)
    messages.success(request, "You've been logged out successfully!")
    return redirect('users:login')

def notifications(request, id):
    user = CustomUser.objects.get(id=id)
    try:
        book = Book.objects.get(borrower=request.user)
    except Book.DoesNotExist:
        book=None
    context = {'book': book, 'user': user}
    return render(request, 'users/notifications.html', context)

users/templates/users/login.html
{% extends "base.html" %}

{% block title %}
    Login 
{% endblock title %}

{% block header %}
    <p>
        <a href="{% url 'core:index' %}">LMS</a> 
    </p>
{% endblock header %}

{% block content %}
    {% if message %}
        <p>{{ message }}</p>
    {% endif %}
    <form action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button>Log in</button>
        <input type="hidden" name="next" value="{% url 'core:index' %}">
    </form>
    <a href="{% url 'users:signup' %}"><button>Sign up</button></a>
{% endblock content %}

users/templates/users/notifications.html
{% extends "base.html" %}

{% block title %}
    Notifications
{% endblock title %}

{% block header %}
    <p>
        <a href="{% url 'core:index' %}">LMS</a> - 
        Hello, {{ user.username }} - 
        <a href="{% url 'users:signout' %}">Sign Out</a> - 
        <a href="{% url 'core:new_book' %}">Add book</a> -
    </p>
{% endblock header %}

{% block content %}
    {% if book %}
        {% if book.is_due %}
            <p>You are reminded to return: {{ book.title }}</p>
        {% else %}
            <p>You are reminded that the return date for <a href="{% url 'core:details' book.uuid %}">"{{ book.title }}"</a> is {{ book.due_date|date:'M d, Y H:m' }}</p>
        {% endif %}
    {% else %}
        <p>No notifications!</p>
    {% endif %}
{% endblock content %}

users/templates/users/profile.html
{% extends "base.html" %}

{% block title %}
    {{ user.username }}
{% endblock title %}

{% block header %}
    <p>
        <a href="{% url 'core:index' %}">LMS</a> - 
        <a href="{% url 'users:signout' %}">Sign Out</a> - 
    </p>
{% endblock header %}

{% block content %}
    <img src="{{ user.profile_picture.url }}" width="70" height="70">
    <h3>@{{ user.username }}</h3>
    <p>Student No: {{ user.std_number }}</p>
    <p>First Name: {{ user.first_name }}</p>
    <p>Last Name: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>
    <hr>
    <!-- <p><a href="{% url 'users:notifications' user.id %}">Notifications</a></p>  datetime information not yet functional -->
    <button type='button' disabled>Notifications</button>
    <h4>Borrowed Books</h4>
    <table>
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Publisher</th>
            <th>Date Borrowed</th>
        </tr>
        {% for book in books %}
        <tr>
            <td>{{ book.title }}</td>
            <td>{{ book.author }}</td>
            <td>{{ book.publisher }}</td>
            <td>{{ book.date_borrowed }}</td>
        </tr>
    </table>
        {% empty %}
            <p>Borrowed books will appear here!</p>
        {% endfor %}
{% endblock content %}

users/templates/users/signup.html
{% extends "base.html" %}

{% block title %}
    Signup 
{% endblock title %}

{% block header %}
    <p>
        <a href="{% url 'core:index' %}">LMS</a> 
    </p>
{% endblock header %}

{% block content %}
    <form action="{% url 'users:signup' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button name="submit">Signup</button>
    </form>
{% endblock content %}