core/urls.py
from xml.dom.minidom import Document
from django.urls import path
from . import views
from lms.settings import MEDIA_URL,MEDIA_ROOT, STATIC_ROOT, STATIC_URL
from django.conf.urls.static import static

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('catalog/', views.catalog, name='catalog'),
    path('book/<str:uuid>/',views.details,name='details'),
    path('request_book/<str:uuid>/', views.request_book, name='request_book'),
    path('new_book/', views.new_book, name='new_book'),
    path('return_book/<str:uuid>/', views.return_book, name='return_book'),
    path('take_book/<str:uuid>/', views.take_book, name='take_book'),
    path('searched/', views.searched, name='searched'),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

urlpatterns += static(STATIC_URL, document_root=STATIC_ROOT)

lms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('users/',include('users.urls')),
]

users/urls.py
from django.urls import path, include
from.import views
from lms.settings import MEDIA_URL,MEDIA_ROOT, STATIC_ROOT, STATIC_URL
from django.conf.urls.static import static

app_name='users'

urlpatterns = [
    path('login/', views.LoginPageView.as_view(), name='login'),
    path('signup/',views.SignUpView.as_view(), name='signup'),
    path('profile/<int:id>/', views.profile, name='profile'),
    path('signout/', views.signout, name='signout'),
    path('notifications/<int:id>/', views.notifications, name='notifications'),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

urlpatterns += static(STATIC_URL, document_root=STATIC_ROOT)

core/models.py
from django.db import models
from users.models import CustomUser
import uuid
from datetime import datetime

genres = [
    ('SciFi', 'SciFi'),
    ('Romance', 'Romance'),
    ('Thriller', 'Thriller'),
    ('Kids', 'Kids'),
    ('Educational', 'Educational'),
    ('Memoir', 'Memoir'),
    ('Business', 'Business'),
    ('Action', 'Action'),
]

status_choices = [
    ('A', 'Available'),
    ('R', 'Requested'),
    ('T', 'Taken')
]

class Book(models.Model):
    title = models.CharField(max_length=50)
    author = models.CharField(max_length=50)
    publisher = models.CharField(max_length=50)
    summary = models.TextField()
    cover_photo = models.ImageField(upload_to="cover_images")
    genre = models.CharField(max_length=20, choices=genres)
    status = models.CharField(max_length=50, choices=status_choices, default='A')
    uuid = models.UUIDField(default=uuid.uuid4)
    borrower = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True)
    date_borrowed = models.DateTimeField(null=True, blank=True, default=None)
    due_date = models.DateTimeField(null=True, blank=True, default=None)
    no_borrowed = models.IntegerField(default=0)

    class Meta:
        permissions = (('can_change_status', 'Change the status of the book'),
                        ('can_request_book', 'Can request for a book to borrow'),
                        ('can_return_book', 'Can return a borrowed book'))

    def __str__(self) -> str:
        return self.title

    @property
    def is_due(self):
        return bool(self.status=='T' and datetime.now() > self.due_date)

class BookInstance(models.Model):
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=63)
    publisher = models.CharField(max_length=63)
    borrower = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    date_borrowed = models.DateTimeField(null=True, blank=True, default=None)

    def __str__(self):
        return self.title 

templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>
            {% block title %}
            {% endblock title %}
        </title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        {% block header %}
            <p>
                <a href="{% url 'core:index' %}">LMS</a> - 
                {% if user.is_authenticated %}
                    Hello, {{ user.username }} - 
                    <a href="{% url 'users:signout' %}">Sign Out</a> - 
                    {% if perms.core.add_book %}
                        <a href="{% url 'core:new_book' %}">Add book</a> -
                    {% endif %}
                    {% if user.role == 'Student' %}
                        <a href="{% url 'users:profile' user.id %}">Profile</a> -
                    {% endif %}
                    <a href="{% url 'core:catalog' %}">Catalog</a> -
                {% else %}
                    <a href="{% url 'users:login' %}">SignIn</a> -
                    <a href="{% url 'users:signup' %}">Sign Up</a> -
                {% endif %}
            </p>
        {% endblock header %}
        {% block content %}
        {% endblock content %}
        <script src="" async defer></script>
    </body>
</html>